// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaign.proto

package campaign

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PromotedObjectType int32

const (
	PromotedObjectType_PROMOTED_OBJECT_TYPE_APP_ANDROID PromotedObjectType = 0
	PromotedObjectType_PROMOTED_OBJECT_TYPE_APP_IOS     PromotedObjectType = 1
	PromotedObjectType_PROMOTED_OBJECT_TYPE_LINK        PromotedObjectType = 2
)

var PromotedObjectType_name = map[int32]string{
	0: "PROMOTED_OBJECT_TYPE_APP_ANDROID",
	1: "PROMOTED_OBJECT_TYPE_APP_IOS",
	2: "PROMOTED_OBJECT_TYPE_LINK",
}
var PromotedObjectType_value = map[string]int32{
	"PROMOTED_OBJECT_TYPE_APP_ANDROID": 0,
	"PROMOTED_OBJECT_TYPE_APP_IOS":     1,
	"PROMOTED_OBJECT_TYPE_LINK":        2,
}

func (x PromotedObjectType) String() string {
	return proto.EnumName(PromotedObjectType_name, int32(x))
}
func (PromotedObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{0}
}

type BudgetMode int32

const (
	BudgetMode_BUDGET_MODE_INFINITE BudgetMode = 0
	BudgetMode_BUDGET_MODE_TOTAL    BudgetMode = 1
	BudgetMode_BUDGET_MODE_DAY      BudgetMode = 2
)

var BudgetMode_name = map[int32]string{
	0: "BUDGET_MODE_INFINITE",
	1: "BUDGET_MODE_TOTAL",
	2: "BUDGET_MODE_DAY",
}
var BudgetMode_value = map[string]int32{
	"BUDGET_MODE_INFINITE": 0,
	"BUDGET_MODE_TOTAL":    1,
	"BUDGET_MODE_DAY":      2,
}

func (x BudgetMode) String() string {
	return proto.EnumName(BudgetMode_name, int32(x))
}
func (BudgetMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{1}
}

type CampaignStatus int32

const (
	CampaignStatus_CAMPAIGN_STUTAUS_DELETE                   CampaignStatus = 0
	CampaignStatus_CAMPAIGN_STUTAUS_DELIVERY_OK              CampaignStatus = 1
	CampaignStatus_CAMPAIGN_STUTAUS_CREATE                   CampaignStatus = 2
	CampaignStatus_CAMPAIGN_STUTAUS_AUDIT                    CampaignStatus = 3
	CampaignStatus_CAMPAIGN_STUTAUS_AUDIT_DENY               CampaignStatus = 4
	CampaignStatus_CAMPAIGN_STUTAUS_NOT_START                CampaignStatus = 5
	CampaignStatus_CAMPAIGN_STUTAUS_BUDGET_EXCEED            CampaignStatus = 6
	CampaignStatus_CAMPAIGN_STUTAUS_ADVERTISER_BUDGET_EXCEED CampaignStatus = 7
	CampaignStatus_CAMPAIGN_STUTAUS_BALANCE_EXCEED           CampaignStatus = 8
	CampaignStatus_CAMPAIGN_STUTAUS_DONE                     CampaignStatus = 9
)

var CampaignStatus_name = map[int32]string{
	0: "CAMPAIGN_STUTAUS_DELETE",
	1: "CAMPAIGN_STUTAUS_DELIVERY_OK",
	2: "CAMPAIGN_STUTAUS_CREATE",
	3: "CAMPAIGN_STUTAUS_AUDIT",
	4: "CAMPAIGN_STUTAUS_AUDIT_DENY",
	5: "CAMPAIGN_STUTAUS_NOT_START",
	6: "CAMPAIGN_STUTAUS_BUDGET_EXCEED",
	7: "CAMPAIGN_STUTAUS_ADVERTISER_BUDGET_EXCEED",
	8: "CAMPAIGN_STUTAUS_BALANCE_EXCEED",
	9: "CAMPAIGN_STUTAUS_DONE",
}
var CampaignStatus_value = map[string]int32{
	"CAMPAIGN_STUTAUS_DELETE":                   0,
	"CAMPAIGN_STUTAUS_DELIVERY_OK":              1,
	"CAMPAIGN_STUTAUS_CREATE":                   2,
	"CAMPAIGN_STUTAUS_AUDIT":                    3,
	"CAMPAIGN_STUTAUS_AUDIT_DENY":               4,
	"CAMPAIGN_STUTAUS_NOT_START":                5,
	"CAMPAIGN_STUTAUS_BUDGET_EXCEED":            6,
	"CAMPAIGN_STUTAUS_ADVERTISER_BUDGET_EXCEED": 7,
	"CAMPAIGN_STUTAUS_BALANCE_EXCEED":           8,
	"CAMPAIGN_STUTAUS_DONE":                     9,
}

func (x CampaignStatus) String() string {
	return proto.EnumName(CampaignStatus_name, int32(x))
}
func (CampaignStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{2}
}

type CampaignConfigStatus int32

const (
	CampaignConfigStatus_CAMPAIGN_CONFIG_STATUS_DELETE  CampaignConfigStatus = 0
	CampaignConfigStatus_CAMPAIGN_CONFIG_STATUS_ENABLE  CampaignConfigStatus = 1
	CampaignConfigStatus_CAMPAIGN_CONFIG_STATUS_DISABLE CampaignConfigStatus = 2
)

var CampaignConfigStatus_name = map[int32]string{
	0: "CAMPAIGN_CONFIG_STATUS_DELETE",
	1: "CAMPAIGN_CONFIG_STATUS_ENABLE",
	2: "CAMPAIGN_CONFIG_STATUS_DISABLE",
}
var CampaignConfigStatus_value = map[string]int32{
	"CAMPAIGN_CONFIG_STATUS_DELETE":  0,
	"CAMPAIGN_CONFIG_STATUS_ENABLE":  1,
	"CAMPAIGN_CONFIG_STATUS_DISABLE": 2,
}

func (x CampaignConfigStatus) String() string {
	return proto.EnumName(CampaignConfigStatus_name, int32(x))
}
func (CampaignConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{3}
}

type OperateData struct {
	CampaignId           uint64   `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperateData) Reset()         { *m = OperateData{} }
func (m *OperateData) String() string { return proto.CompactTextString(m) }
func (*OperateData) ProtoMessage()    {}
func (*OperateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{0}
}
func (m *OperateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperateData.Unmarshal(m, b)
}
func (m *OperateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperateData.Marshal(b, m, deterministic)
}
func (dst *OperateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperateData.Merge(dst, src)
}
func (m *OperateData) XXX_Size() int {
	return xxx_messageInfo_OperateData.Size(m)
}
func (m *OperateData) XXX_DiscardUnknown() {
	xxx_messageInfo_OperateData.DiscardUnknown(m)
}

var xxx_messageInfo_OperateData proto.InternalMessageInfo

func (m *OperateData) GetCampaignId() uint64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

type AddRequest struct {
	AdvertiserId         uint64             `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	CampaignName         string             `protobuf:"bytes,2,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	PromotedObjectType   PromotedObjectType `protobuf:"varint,3,opt,name=promoted_object_type,json=promotedObjectType,proto3,enum=PromotedObjectType" json:"promoted_object_type,omitempty"`
	BudgetMode           BudgetMode         `protobuf:"varint,4,opt,name=budget_mode,json=budgetMode,proto3,enum=BudgetMode" json:"budget_mode,omitempty"`
	Budget               uint64             `protobuf:"varint,5,opt,name=budget,proto3" json:"budget,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{1}
}
func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (dst *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(dst, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetAdvertiserId() uint64 {
	if m != nil {
		return m.AdvertiserId
	}
	return 0
}

func (m *AddRequest) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *AddRequest) GetPromotedObjectType() PromotedObjectType {
	if m != nil {
		return m.PromotedObjectType
	}
	return PromotedObjectType_PROMOTED_OBJECT_TYPE_APP_ANDROID
}

func (m *AddRequest) GetBudgetMode() BudgetMode {
	if m != nil {
		return m.BudgetMode
	}
	return BudgetMode_BUDGET_MODE_INFINITE
}

func (m *AddRequest) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

type AddResponse struct {
	Code                 uint64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *OperateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{2}
}
func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (dst *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(dst, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddResponse) GetData() *OperateData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest struct {
	AdvertiserId         uint64     `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	CampaignId           uint64     `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CampaignName         string     `protobuf:"bytes,3,opt,name=campaign_name,json=campaignName,proto3" json:"campaign_name,omitempty"`
	BudgetMode           BudgetMode `protobuf:"varint,4,opt,name=budget_mode,json=budgetMode,proto3,enum=BudgetMode" json:"budget_mode,omitempty"`
	Budget               uint64     `protobuf:"varint,5,opt,name=budget,proto3" json:"budget,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{3}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetAdvertiserId() uint64 {
	if m != nil {
		return m.AdvertiserId
	}
	return 0
}

func (m *UpdateRequest) GetCampaignId() uint64 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *UpdateRequest) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *UpdateRequest) GetBudgetMode() BudgetMode {
	if m != nil {
		return m.BudgetMode
	}
	return BudgetMode_BUDGET_MODE_INFINITE
}

func (m *UpdateRequest) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

type UpdateResponse struct {
	Code                 uint64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *OperateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{4}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateResponse) GetData() *OperateData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRequestFiltering struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequestFiltering) Reset()         { *m = GetRequestFiltering{} }
func (m *GetRequestFiltering) String() string { return proto.CompactTextString(m) }
func (*GetRequestFiltering) ProtoMessage()    {}
func (*GetRequestFiltering) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{5}
}
func (m *GetRequestFiltering) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequestFiltering.Unmarshal(m, b)
}
func (m *GetRequestFiltering) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequestFiltering.Marshal(b, m, deterministic)
}
func (dst *GetRequestFiltering) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequestFiltering.Merge(dst, src)
}
func (m *GetRequestFiltering) XXX_Size() int {
	return xxx_messageInfo_GetRequestFiltering.Size(m)
}
func (m *GetRequestFiltering) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequestFiltering.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequestFiltering proto.InternalMessageInfo

type GetRequest struct {
	AdvertiserId         uint64               `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	Filtering            *GetRequestFiltering `protobuf:"bytes,2,opt,name=filtering,proto3" json:"filtering,omitempty"`
	Page                 uint64               `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint64               `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{6}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetAdvertiserId() uint64 {
	if m != nil {
		return m.AdvertiserId
	}
	return 0
}

func (m *GetRequest) GetFiltering() *GetRequestFiltering {
	if m != nil {
		return m.Filtering
	}
	return nil
}

func (m *GetRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{7}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

type UpdateStatusRequest struct {
	AdvertiserId         int32                `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	CampaignId           int32                `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ConfigStatus         CampaignConfigStatus `protobuf:"varint,3,opt,name=config_status,json=configStatus,proto3,enum=CampaignConfigStatus" json:"config_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateStatusRequest) Reset()         { *m = UpdateStatusRequest{} }
func (m *UpdateStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStatusRequest) ProtoMessage()    {}
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{8}
}
func (m *UpdateStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStatusRequest.Unmarshal(m, b)
}
func (m *UpdateStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStatusRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStatusRequest.Merge(dst, src)
}
func (m *UpdateStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStatusRequest.Size(m)
}
func (m *UpdateStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStatusRequest proto.InternalMessageInfo

func (m *UpdateStatusRequest) GetAdvertiserId() int32 {
	if m != nil {
		return m.AdvertiserId
	}
	return 0
}

func (m *UpdateStatusRequest) GetCampaignId() int32 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *UpdateStatusRequest) GetConfigStatus() CampaignConfigStatus {
	if m != nil {
		return m.ConfigStatus
	}
	return CampaignConfigStatus_CAMPAIGN_CONFIG_STATUS_DELETE
}

type UpdateStatusResponse struct {
	Code                 uint64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *OperateData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateStatusResponse) Reset()         { *m = UpdateStatusResponse{} }
func (m *UpdateStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStatusResponse) ProtoMessage()    {}
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_65fd711ee1ca8748, []int{9}
}
func (m *UpdateStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStatusResponse.Unmarshal(m, b)
}
func (m *UpdateStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStatusResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStatusResponse.Merge(dst, src)
}
func (m *UpdateStatusResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStatusResponse.Size(m)
}
func (m *UpdateStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStatusResponse proto.InternalMessageInfo

func (m *UpdateStatusResponse) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateStatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateStatusResponse) GetData() *OperateData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*OperateData)(nil), "OperateData")
	proto.RegisterType((*AddRequest)(nil), "AddRequest")
	proto.RegisterType((*AddResponse)(nil), "AddResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*GetRequestFiltering)(nil), "GetRequestFiltering")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*UpdateStatusRequest)(nil), "UpdateStatusRequest")
	proto.RegisterType((*UpdateStatusResponse)(nil), "UpdateStatusResponse")
	proto.RegisterEnum("PromotedObjectType", PromotedObjectType_name, PromotedObjectType_value)
	proto.RegisterEnum("BudgetMode", BudgetMode_name, BudgetMode_value)
	proto.RegisterEnum("CampaignStatus", CampaignStatus_name, CampaignStatus_value)
	proto.RegisterEnum("CampaignConfigStatus", CampaignConfigStatus_name, CampaignConfigStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
}

type campaignServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampaignServiceClient(cc *grpc.ClientConn) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/CampaignService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/CampaignService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/CampaignService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, "/CampaignService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
type CampaignServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
}

func RegisterCampaignServiceServer(s *grpc.Server, srv CampaignServiceServer) {
	s.RegisterService(&_CampaignService_serviceDesc, srv)
}

func _CampaignService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampaignService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampaignService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampaignService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampaignService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampaignService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CampaignService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CampaignService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CampaignService_Get_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _CampaignService_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaign.proto",
}

func init() { proto.RegisterFile("campaign.proto", fileDescriptor_campaign_65fd711ee1ca8748) }

var fileDescriptor_campaign_65fd711ee1ca8748 = []byte{
	// 822 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0xb6, 0x6c, 0x27, 0xbb, 0x69, 0x39, 0x8e, 0xe8, 0xd8, 0x8b, 0xd7, 0xd9, 0xdd, 0x18, 0x2d,
	0x87, 0x10, 0x40, 0x07, 0x73, 0xa3, 0x8a, 0x83, 0x62, 0x4d, 0x5c, 0x62, 0x1d, 0xc9, 0x25, 0x8f,
	0xb7, 0xc8, 0x81, 0x1a, 0x14, 0x6b, 0xe2, 0x12, 0x85, 0x2d, 0x61, 0x4d, 0xb6, 0x6a, 0x97, 0x0b,
	0x4f, 0x01, 0xaf, 0xc3, 0x85, 0xb7, 0xe0, 0xc6, 0x8b, 0x50, 0x92, 0xac, 0x58, 0xb6, 0xb4, 0xfc,
	0x54, 0x91, 0x93, 0x66, 0xba, 0xbf, 0xf9, 0xd4, 0xfd, 0xf5, 0x74, 0x0f, 0x34, 0x67, 0xee, 0x22,
	0x74, 0xfd, 0xf9, 0x52, 0x0b, 0x57, 0x81, 0x08, 0x54, 0x0d, 0x64, 0x3b, 0xe4, 0x2b, 0x57, 0x70,
	0xc3, 0x15, 0x2e, 0x9e, 0x82, 0x9c, 0x01, 0x98, 0xef, 0x75, 0xa4, 0x9e, 0x74, 0x56, 0x77, 0x20,
	0x33, 0x99, 0x9e, 0xfa, 0xa7, 0x04, 0xa0, 0x7b, 0x9e, 0xc3, 0x7f, 0xbc, 0xe3, 0x91, 0xc0, 0x97,
	0x70, 0xe8, 0x7a, 0x6f, 0xf8, 0x4a, 0xf8, 0x11, 0x5f, 0x6d, 0x4e, 0x34, 0x36, 0x46, 0xd3, 0x8b,
	0x41, 0xf7, 0xa4, 0x4b, 0x77, 0xc1, 0x3b, 0xd5, 0x9e, 0x74, 0x76, 0xe0, 0x34, 0x32, 0xa3, 0xe5,
	0x2e, 0x38, 0x12, 0x68, 0x85, 0xab, 0x60, 0x11, 0x08, 0xee, 0xb1, 0xe0, 0xe6, 0x7b, 0x3e, 0x13,
	0x4c, 0xbc, 0x0d, 0x79, 0xa7, 0xd6, 0x93, 0xce, 0x9a, 0xfd, 0x63, 0x6d, 0xbc, 0x76, 0xda, 0x89,
	0x8f, 0xbe, 0x0d, 0xb9, 0x83, 0x61, 0xc1, 0x86, 0x9f, 0x81, 0x7c, 0x73, 0xe7, 0xcd, 0xb9, 0x60,
	0x8b, 0xc0, 0xe3, 0x9d, 0x7a, 0x72, 0x5a, 0xd6, 0x2e, 0x12, 0xdb, 0x55, 0xe0, 0x71, 0x07, 0x6e,
	0xee, 0xd7, 0xf8, 0x04, 0xf6, 0xd3, 0x5d, 0x67, 0x2f, 0x89, 0x7b, 0xbd, 0x53, 0xbf, 0x05, 0x39,
	0x49, 0x32, 0x0a, 0x83, 0x65, 0xc4, 0x11, 0xa1, 0x3e, 0x8b, 0xd9, 0xd2, 0xe4, 0x92, 0x35, 0x76,
	0xe0, 0xd1, 0x82, 0x47, 0x91, 0x3b, 0xcf, 0xd2, 0xc9, 0xb6, 0xd8, 0x83, 0xba, 0xe7, 0x0a, 0x37,
	0x89, 0x5c, 0xee, 0x37, 0xb4, 0x9c, 0xbe, 0x4e, 0xe2, 0x51, 0x7f, 0x93, 0xe0, 0x70, 0x1a, 0x7a,
	0xae, 0xe0, 0xff, 0x49, 0xc7, 0x9d, 0xe2, 0x54, 0x77, 0x8b, 0x53, 0x14, 0xba, 0x56, 0x22, 0xf4,
	0xff, 0xa3, 0xd0, 0x77, 0xd0, 0xcc, 0x32, 0x78, 0x20, 0x91, 0xda, 0x70, 0x3c, 0xe4, 0x62, 0x2d,
	0xd0, 0xa5, 0xff, 0x83, 0xe0, 0x2b, 0x7f, 0x39, 0x57, 0x7f, 0x91, 0x00, 0x36, 0xf6, 0x7f, 0x27,
	0x5c, 0x1f, 0x0e, 0x6e, 0x33, 0x82, 0x24, 0x10, 0xb9, 0xdf, 0xd2, 0x4a, 0xc8, 0x9d, 0x0d, 0x2c,
	0x4e, 0x27, 0x8c, 0xe3, 0xae, 0xa5, 0xe9, 0xc4, 0x6b, 0x3c, 0x81, 0x83, 0xf8, 0xcb, 0x22, 0xff,
	0x5d, 0x2a, 0x5c, 0xdd, 0x79, 0x1c, 0x1b, 0x26, 0xfe, 0x3b, 0xae, 0x1e, 0x82, 0x9c, 0x50, 0xa6,
	0x72, 0xa8, 0xbf, 0x4a, 0x70, 0x9c, 0x2a, 0x34, 0x11, 0xae, 0xb8, 0x8b, 0xfe, 0x36, 0xe0, 0xbd,
	0x7f, 0xae, 0xf4, 0xde, 0x56, 0xa5, 0xbf, 0x84, 0xc3, 0x59, 0xb0, 0xbc, 0xf5, 0xe7, 0x2c, 0x4a,
	0xd8, 0xd7, 0x6d, 0xd2, 0xd6, 0x06, 0x6b, 0xcc, 0x20, 0xf1, 0xae, 0x7f, 0xdd, 0x98, 0xe5, 0x76,
	0xea, 0x2d, 0xb4, 0xb6, 0x03, 0x7b, 0x98, 0x02, 0x9e, 0xff, 0x04, 0x58, 0x6c, 0x5a, 0xfc, 0x18,
	0x7a, 0x63, 0xc7, 0xbe, 0xb2, 0x29, 0x31, 0x98, 0x7d, 0xf1, 0x35, 0x19, 0x50, 0x46, 0xaf, 0xc7,
	0x84, 0xe9, 0xe3, 0x31, 0xd3, 0x2d, 0xc3, 0xb1, 0x4d, 0x43, 0xa9, 0x60, 0x0f, 0x9e, 0xbd, 0x17,
	0x65, 0xda, 0x13, 0x45, 0xc2, 0xe7, 0xf0, 0xb4, 0x14, 0x31, 0x32, 0xad, 0x57, 0x4a, 0xf5, 0xdc,
	0x01, 0xd8, 0xdc, 0x68, 0xec, 0x40, 0xeb, 0x62, 0x6a, 0x0c, 0x09, 0x65, 0x57, 0xb6, 0x41, 0x98,
	0x69, 0x5d, 0x9a, 0x96, 0x49, 0x89, 0x52, 0xc1, 0x36, 0x7c, 0x90, 0xf7, 0x50, 0x9b, 0xea, 0x23,
	0x45, 0xc2, 0x63, 0x38, 0xca, 0x9b, 0x0d, 0xfd, 0x5a, 0xa9, 0x9e, 0xff, 0x51, 0x85, 0x66, 0xa6,
	0x6f, 0xaa, 0x1d, 0x9e, 0xc0, 0x87, 0x03, 0xfd, 0x6a, 0xac, 0x9b, 0x43, 0x8b, 0x4d, 0xe8, 0x94,
	0xea, 0xd3, 0x09, 0x33, 0xc8, 0x88, 0x24, 0xdc, 0x3d, 0x78, 0x56, 0xe6, 0x34, 0x5f, 0x13, 0xe7,
	0x9a, 0xd9, 0xaf, 0x14, 0xa9, 0xf4, 0xf8, 0xc0, 0x21, 0x3a, 0x25, 0x4a, 0x15, 0xbb, 0xf0, 0xa4,
	0xe0, 0xd4, 0xa7, 0x86, 0x49, 0x95, 0x1a, 0x9e, 0xc2, 0x49, 0xb9, 0x8f, 0x19, 0xc4, 0xba, 0x56,
	0xea, 0xf8, 0x02, 0xba, 0x05, 0x80, 0x65, 0x53, 0x36, 0xa1, 0xba, 0x43, 0x95, 0x3d, 0x54, 0xe1,
	0x45, 0xc1, 0xbf, 0xce, 0x98, 0x7c, 0x33, 0x20, 0xc4, 0x50, 0xf6, 0xf1, 0x73, 0xf8, 0xa4, 0xf8,
	0x13, 0xe3, 0x35, 0x71, 0xa8, 0x39, 0x21, 0xce, 0x0e, 0xfc, 0x11, 0xbe, 0x84, 0xd3, 0x22, 0xa5,
	0x3e, 0xd2, 0xad, 0x01, 0xc9, 0x40, 0x8f, 0xf1, 0x29, 0xb4, 0x8b, 0x9a, 0xd8, 0x16, 0x51, 0x0e,
	0xce, 0x7f, 0x96, 0xa0, 0x55, 0x76, 0x7d, 0xf1, 0x23, 0x78, 0x7e, 0x7f, 0x66, 0x60, 0x5b, 0x97,
	0xe6, 0x30, 0x4e, 0x83, 0xe6, 0xa5, 0x7e, 0x3f, 0x84, 0x58, 0xfa, 0xc5, 0x88, 0x28, 0xd2, 0x56,
	0xc6, 0x3b, 0x2c, 0xe6, 0x24, 0xc1, 0x54, 0xfb, 0xbf, 0x4b, 0x70, 0x74, 0x5f, 0x61, 0xbe, 0x7a,
	0xe3, 0xcf, 0x38, 0xaa, 0x50, 0xd3, 0x3d, 0x0f, 0x65, 0x6d, 0xf3, 0xec, 0x75, 0x1b, 0x5a, 0xee,
	0x79, 0x50, 0x2b, 0xf8, 0x29, 0xec, 0xa7, 0x2d, 0x85, 0x4d, 0x6d, 0x6b, 0xb0, 0x77, 0x8f, 0xb4,
	0xed, 0x31, 0xa9, 0x56, 0x62, 0xc2, 0x21, 0x17, 0x28, 0xe7, 0x26, 0x50, 0xb7, 0xa1, 0xe5, 0x67,
	0x47, 0x05, 0xbf, 0x82, 0x46, 0xbe, 0x47, 0xb1, 0xa5, 0x95, 0xcc, 0x92, 0x6e, 0x5b, 0x2b, 0x6b,
	0x64, 0xb5, 0x72, 0xb3, 0x9f, 0x3c, 0xee, 0x5f, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x03, 0x67,
	0xb9, 0xff, 0xee, 0x07, 0x00, 0x00,
}
